// Copyright © Erickson Lopez. MIT License.
using System;
using System.Threading;
using System.Threading.Tasks;

namespace EricksonLopez.Messaging.Generators.Tests;

using System.Collections.Immutable;
using System.Linq;
using AwesomeAssertions;
using EricksonLopez.Messaging.Contracts;
using EricksonLopez.Messaging.Generators.Models;
using EricksonLopez.Messaging.Generators.Tests.Common;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using NSubstitute;
using Xunit;

[Trait("Category", "Roslyn")]
public class MessagingIncrementalGeneratorTests
{
    private static string NormalizeLineEndings(string text) =>
        text.Replace("\r\n", "\n").Trim();

    private static (Compilation Compilation, GeneratorDriverRunResult RunResult) RunGenerator(string source)
    {
        var compilation = RoslynTestCompilationFactory.CreateCompilation(source);

        var generator = new MessagingIncrementalGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        diagnostics.Should().BeEmpty();
        return (outputCompilation, driver.GetRunResult());
    }

    [Fact]
    public void Generator_DiscoversHandlers_WithCustomMessageTypeAttribute_EmitsExactRegistrations()
    {
        // Arrange
        const string userSource = """
            namespace Sample.Tests;

            using EricksonLopez.Messaging.Attributes;
            using EricksonLopez.Result;

            [MessageType("sample.test-event.v1")]
            public sealed record SampleTestEvent(string Text) : IMessage;

            public sealed class SampleTestEventHandler : IMessageHandler<SampleTestEvent>
            {
                public ValueTask<Result> HandleAsync(
                    SampleTestEvent message,
                    MessageContext context,
                    CancellationToken cancellationToken = default)
                {
                    return ValueTask.FromResult(Result.Success());
                }
            }
            """;

        // Act
        var (_, runResult) = RunGenerator(userSource);

        // Assert
        runResult.GeneratedTrees.Should().ContainSingle();
        var generatedCode = runResult.GeneratedTrees[0].ToString();

        const string expected = """
            // <auto-generated/>
            #nullable enable

            namespace EricksonLopez.Messaging.Generated
            {
                using System.Text.Json.Serialization;

                /// <summary>
                /// Compile-time source-generated JsonSerializerContext for discovered message types.
                /// </summary>
                [JsonSourceGenerationOptions(
                    WriteIndented = false,
                    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
                    GenerationMode = JsonSourceGenerationMode.Default)]
                [JsonSerializable(typeof(global::Sample.Tests.SampleTestEvent))]
                internal sealed partial class GeneratedMessagingJsonSerializerContext : JsonSerializerContext
                {
                }
            }

            namespace Microsoft.Extensions.DependencyInjection
            {
                using System;
                using EricksonLopez.Messaging.Contracts;

                /// <summary>
                /// Compile-time generated extensions for zero-reflection messaging handler registration.
                /// </summary>
                public static class GeneratedMessagingServiceCollectionExtensions
                {
                    /// <summary>
                    /// Registers all compile-time discovered message handlers and JSON serialization context without runtime reflection.
                    /// </summary>
                    public static IServiceCollection AddGeneratedMessagingHandlers(this IServiceCollection services)
                    {
                        services.AddSingleton<System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver>(
                            EricksonLopez.Messaging.Generated.GeneratedMessagingJsonSerializerContext.Default);

                        // Handler for message 'sample.test-event.v1'
                        services.AddMessageHandler<global::Sample.Tests.SampleTestEvent, global::Sample.Tests.SampleTestEventHandler>();

                        return services;
                    }
                }
            }
            """;

        NormalizeLineEndings(generatedCode).Should().Be(NormalizeLineEndings(expected));
    }

    [Fact]
    public void Generator_HandlerWithoutMessageTypeAttribute_FallsBackToTypeName()
    {
        // Arrange - Message without [MessageType] attribute, plus another attribute with no args and non-string arg
        const string userSource = """
            namespace Sample.Tests;

            [AttributeUsage(AttributeTargets.Class)]
            public sealed class NoArgAttribute : Attribute
            {
            }

            [AttributeUsage(AttributeTargets.Class)]
            public sealed class IntArgAttribute : Attribute
            {
                public IntArgAttribute(int value) { }
            }

            [NoArg]
            [IntArg(42)]
            [Serializable]
            public sealed record EventWithoutAttribute(int Id) : IMessage;

            public sealed class HandlerWithoutAttribute : IMessageHandler<EventWithoutAttribute>
            {
                public ValueTask<Result> HandleAsync(
                    EventWithoutAttribute message,
                    MessageContext context,
                    CancellationToken cancellationToken = default)
                {
                    return ValueTask.FromResult(Result.Success());
                }
            }
            """;

        // Act
        var (_, runResult) = RunGenerator(userSource);

        // Assert
        runResult.GeneratedTrees.Should().ContainSingle();
        var generatedCode = runResult.GeneratedTrees[0].ToString();
        generatedCode.Should().Contain("// Handler for message 'EventWithoutAttribute'");
        generatedCode.Should().Contain("services.AddMessageHandler<global::Sample.Tests.EventWithoutAttribute, global::Sample.Tests.HandlerWithoutAttribute>();");
    }

    [Fact]
    public void Generator_WithAbstractClassesAndNonMatchingInterfaces_IgnoresThem()
    {
        // Arrange
        const string userSource = """
            namespace Sample.Tests;

            [MessageType("valid.message")]
            public sealed record ValidMessage(string Data) : IMessage;

            public abstract class AbstractHandler : IMessageHandler<ValidMessage>
            {
                public abstract ValueTask<Result> HandleAsync(ValidMessage message, MessageContext context, CancellationToken cancellationToken);
            }

            public class ClassWithoutBaseTypes
            {
                public void DoSomething() { }
            }

            public class NonGenericInterfaceClass : IDisposable
            {
                public void Dispose() { }
            }

            public class GenericNonHandlerClass : IEquatable<GenericNonHandlerClass>
            {
                public bool Equals(GenericNonHandlerClass? other) => true;
            }

            public struct StructType : IDisposable
            {
                public void Dispose() { }
            }

            public enum SampleEnum { Value1, Value2 }

            public interface ISomeInterface { }
            """;

        // Act
        var (_, runResult) = RunGenerator(userSource);

        // Assert
        runResult.GeneratedTrees.Should().ContainSingle();
        var generatedCode = runResult.GeneratedTrees[0].ToString();
        generatedCode.Should().Contain("AddGeneratedMessagingHandlers");
        generatedCode.Should().NotContain("AbstractHandler");
        generatedCode.Should().NotContain("ClassWithoutBaseTypes");
        generatedCode.Should().NotContain("NonGenericInterfaceClass");
        generatedCode.Should().NotContain("GenericNonHandlerClass");
    }

    [Fact]
    public void Generator_DiscoversMultipleHandlers_WithDuplicateMessageTypes_EmitsDistinctSerializablesAndAllHandlers()
    {
        // Arrange
        const string userSource = """
            namespace Sample.Multi;

            using EricksonLopez.Messaging.Attributes;

            [MessageType("event.one")]
            public sealed record EventOne : IMessage;

            [MessageType("event.two")]
            public sealed record EventTwo : IMessage;

            public sealed class HandlerOneA : IMessageHandler<EventOne>
            {
                public ValueTask<Result> HandleAsync(EventOne message, MessageContext context, CancellationToken cancellationToken = default) => ValueTask.FromResult(Result.Success());
            }

            public sealed class HandlerOneB : IMessageHandler<EventOne>
            {
                public ValueTask<Result> HandleAsync(EventOne message, MessageContext context, CancellationToken cancellationToken = default) => ValueTask.FromResult(Result.Success());
            }

            public sealed class HandlerTwo : IMessageHandler<EventTwo>
            {
                public ValueTask<Result> HandleAsync(EventTwo message, MessageContext context, CancellationToken cancellationToken = default) => ValueTask.FromResult(Result.Success());
            }
            """;

        // Act
        var (_, runResult) = RunGenerator(userSource);

        // Assert
        runResult.GeneratedTrees.Should().ContainSingle();
        var generatedCode = runResult.GeneratedTrees[0].ToString();

        const string expected = """
            // <auto-generated/>
            #nullable enable

            namespace EricksonLopez.Messaging.Generated
            {
                using System.Text.Json.Serialization;

                /// <summary>
                /// Compile-time source-generated JsonSerializerContext for discovered message types.
                /// </summary>
                [JsonSourceGenerationOptions(
                    WriteIndented = false,
                    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
                    GenerationMode = JsonSourceGenerationMode.Default)]
                [JsonSerializable(typeof(global::Sample.Multi.EventOne))]
                [JsonSerializable(typeof(global::Sample.Multi.EventTwo))]
                internal sealed partial class GeneratedMessagingJsonSerializerContext : JsonSerializerContext
                {
                }
            }

            namespace Microsoft.Extensions.DependencyInjection
            {
                using System;
                using EricksonLopez.Messaging.Contracts;

                /// <summary>
                /// Compile-time generated extensions for zero-reflection messaging handler registration.
                /// </summary>
                public static class GeneratedMessagingServiceCollectionExtensions
                {
                    /// <summary>
                    /// Registers all compile-time discovered message handlers and JSON serialization context without runtime reflection.
                    /// </summary>
                    public static IServiceCollection AddGeneratedMessagingHandlers(this IServiceCollection services)
                    {
                        services.AddSingleton<System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver>(
                            EricksonLopez.Messaging.Generated.GeneratedMessagingJsonSerializerContext.Default);

                        // Handler for message 'event.one'
                        services.AddMessageHandler<global::Sample.Multi.EventOne, global::Sample.Multi.HandlerOneA>();
                        // Handler for message 'event.one'
                        services.AddMessageHandler<global::Sample.Multi.EventOne, global::Sample.Multi.HandlerOneB>();
                        // Handler for message 'event.two'
                        services.AddMessageHandler<global::Sample.Multi.EventTwo, global::Sample.Multi.HandlerTwo>();

                        return services;
                    }
                }
            }
            """;

        NormalizeLineEndings(generatedCode).Should().Be(NormalizeLineEndings(expected));
    }

    [Fact]
    public void Generator_EmptySource_EmitsEmptyExtensionMethod()
    {
        // Arrange
        const string userSource = """
            namespace Sample.Empty;
            public class Dummy { }
            """;

        // Act
        var (_, runResult) = RunGenerator(userSource);

        // Assert
        runResult.GeneratedTrees.Should().ContainSingle();
        var generatedCode = runResult.GeneratedTrees[0].ToString();

        const string expected = """
            // <auto-generated/>
            #nullable enable

            namespace EricksonLopez.Messaging.Generated
            {
                using System.Text.Json.Serialization;

                /// <summary>
                /// Compile-time source-generated JsonSerializerContext for discovered message types.
                /// </summary>
                [JsonSourceGenerationOptions(
                    WriteIndented = false,
                    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
                    GenerationMode = JsonSourceGenerationMode.Default)]
                internal sealed partial class GeneratedMessagingJsonSerializerContext : JsonSerializerContext
                {
                }
            }

            namespace Microsoft.Extensions.DependencyInjection
            {
                using System;
                using EricksonLopez.Messaging.Contracts;

                /// <summary>
                /// Compile-time generated extensions for zero-reflection messaging handler registration.
                /// </summary>
                public static class GeneratedMessagingServiceCollectionExtensions
                {
                    /// <summary>
                    /// Registers all compile-time discovered message handlers and JSON serialization context without runtime reflection.
                    /// </summary>
                    public static IServiceCollection AddGeneratedMessagingHandlers(this IServiceCollection services)
                    {
                        services.AddSingleton<System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver>(
                            EricksonLopez.Messaging.Generated.GeneratedMessagingJsonSerializerContext.Default);


                        return services;
                    }
                }
            }
            """;

        NormalizeLineEndings(generatedCode).Should().Be(NormalizeLineEndings(expected));
    }

    [Fact]
    public void Generator_DiscoversHandlers_WithSyntaxDefinedMessageTypeAttribute()
    {
        // Arrange
        const string userSource = """
            namespace Sample.Syntax;

            [AttributeUsage(AttributeTargets.Class)]
            public sealed class MessageTypeAttribute : Attribute
            {
                public MessageTypeAttribute(string name) { }
            }

            [MessageType("syntax.custom.event")]
            public sealed record SyntaxEvent : IMessage;

            public sealed class SyntaxEventHandler : IMessageHandler<SyntaxEvent>
            {
                public ValueTask<Result> HandleAsync(SyntaxEvent message, MessageContext context, CancellationToken cancellationToken = default) => ValueTask.FromResult(Result.Success());
            }
            """;

        // Act
        var (_, runResult) = RunGenerator(userSource);

        // Assert
        runResult.GeneratedTrees.Should().ContainSingle();
        var generatedCode = runResult.GeneratedTrees[0].ToString();
        generatedCode.Should().Contain("// Handler for message 'syntax.custom.event'");
        generatedCode.Should().Contain("services.AddMessageHandler<global::Sample.Syntax.SyntaxEvent, global::Sample.Syntax.SyntaxEventHandler>();");
    }

    [Fact]
    public void IsCandidateClass_DirectInvocation_ReturnsCorrectResults()
    {
        var tree = CSharpSyntaxTree.ParseText("""
            public abstract class AbstractClass : IDisposable { public void Dispose() {} }
            public class NoBaseListClass { }
            public class ValidClass : IDisposable { public void Dispose() {} }
            public struct StructType { }
            """);
        var root = tree.GetRoot();
        var classes = root.DescendantNodes().OfType<ClassDeclarationSyntax>().ToList();
        var structNode = root.DescendantNodes().OfType<StructDeclarationSyntax>().First();

        var emptyBaseListClass = SyntaxFactory.ClassDeclaration("EmptyBase").WithBaseList(SyntaxFactory.BaseList());

        var method = typeof(MessagingIncrementalGenerator).GetMethod("IsCandidateClass", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!;

        // Abstract class -> false
        ((bool)method.Invoke(null, new object[] { classes[0] })!).Should().BeFalse();
        // No base list -> false
        ((bool)method.Invoke(null, new object[] { classes[1] })!).Should().BeFalse();
        // Base list with 0 types -> false
        ((bool)method.Invoke(null, new object[] { emptyBaseListClass })!).Should().BeFalse();
        // Valid class with base list -> true
        ((bool)method.Invoke(null, new object[] { classes[2] })!).Should().BeTrue();
        // Non-class node -> false
        ((bool)method.Invoke(null, new object[] { structNode })!).Should().BeFalse();
    }

    [Fact]
    public void ResolveMessageTypeName_DirectInvocation_TestsAllAttributeBranches()
    {
        var compilation = RoslynTestCompilationFactory.CreateCompilation("""
            namespace Test;
            using EricksonLopez.Messaging.Attributes;

            [MessageType("custom.bound")]
            public record MsgBound;

            public record MsgNoAttr;

            [AttributeUsage(AttributeTargets.Class)]
            public class OtherAttribute : Attribute { }

            [Other]
            public record MsgOtherAttr;

            [AttributeUsage(AttributeTargets.Class)]
            public class MessageTypeAttribute : Attribute
            {
                public MessageTypeAttribute() {}
                public MessageTypeAttribute(string name) {}
            }

            [MessageType]
            public record MsgEmptyAttr;

            [MessageType()]
            public record MsgEmptyParens;

            [MessageType("syntax.name")]
            public record MsgSyntaxAttr;
            """);

        var msgBound = compilation.GetTypeByMetadataName("Test.MsgBound")!;
        var msgNoAttr = compilation.GetTypeByMetadataName("Test.MsgNoAttr")!;
        var msgOther = compilation.GetTypeByMetadataName("Test.MsgOtherAttr")!;
        var msgEmpty = compilation.GetTypeByMetadataName("Test.MsgEmptyAttr")!;
        var msgEmptyParens = compilation.GetTypeByMetadataName("Test.MsgEmptyParens")!;
        var msgSyntax = compilation.GetTypeByMetadataName("Test.MsgSyntaxAttr")!;

        var method = typeof(MessagingIncrementalGenerator).GetMethod("ResolveMessageTypeName", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!;

        ((string)method.Invoke(null, new object[] { msgBound })!).Should().Be("custom.bound");
        ((string)method.Invoke(null, new object[] { msgNoAttr })!).Should().Be("MsgNoAttr");
        ((string)method.Invoke(null, new object[] { msgOther })!).Should().Be("MsgOtherAttr");
        ((string)method.Invoke(null, new object[] { msgEmpty })!).Should().Be("MsgEmptyAttr");
        ((string)method.Invoke(null, new object[] { msgEmptyParens })!).Should().Be("MsgEmptyParens");
        ((string)method.Invoke(null, new object[] { msgSyntax })!).Should().Be("syntax.name");
    }

    [Fact]
    public void ResolveMessageTypeName_OnMetadataType_TestsConstructorArgumentsPath()
    {
        var metaSource = """
            namespace Lib;
            using EricksonLopez.Messaging.Attributes;

            [MessageType("metadata.bound")]
            public record MetaBound;

            [AttributeUsage(AttributeTargets.Class)]
            public class MessageTypeAttribute : Attribute
            {
                public MessageTypeAttribute() {}
                public MessageTypeAttribute(string name) {}
            }

            [MessageType]
            public record MetaEmpty;
            """;
        var metaComp = RoslynTestCompilationFactory.CreateCompilation(metaSource, "MetaLib");
        using var ms = new System.IO.MemoryStream();
        var emitResult = metaComp.Emit(ms);
        emitResult.Success.Should().BeTrue();
        ms.Seek(0, System.IO.SeekOrigin.Begin);

        var metaRef = MetadataReference.CreateFromStream(ms);
        var consumerComp = CSharpCompilation.Create(
            "Consumer",
            new[] { CSharpSyntaxTree.ParseText("class C {}") },
            new[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(EricksonLopez.Messaging.Attributes.MessageTypeAttribute).Assembly.Location),
                metaRef
            },
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var metaBoundSymbol = consumerComp.GetTypeByMetadataName("Lib.MetaBound")!;
        var metaEmptySymbol = consumerComp.GetTypeByMetadataName("Lib.MetaEmpty")!;

        var method = typeof(MessagingIncrementalGenerator).GetMethod("ResolveMessageTypeName", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!;

        // Tests ConstructorArguments[0].Value -> returns "metadata.bound" directly (ApplicationSyntaxReference is null)
        ((string)method.Invoke(null, new object[] { metaBoundSymbol })!).Should().Be("metadata.bound");

        // Tests ConstructorArguments.Length == 0 on metadata symbol (does not throw IndexOutOfRangeException)
        ((string)method.Invoke(null, new object[] { metaEmptySymbol })!).Should().Be("MetaEmpty");
    }

    [Fact]
    [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2075", Justification = "Reflection test")]
    public void GetHandlerInfo_WhenSymbolNotFoundInSemanticModel_ReturnsNull()
    {
        var semanticModel = NSubstitute.Substitute.For<SemanticModel>();
        var classDecl = SyntaxFactory.ClassDeclaration("MyClass");

        var contextCtor = typeof(GeneratorSyntaxContext).GetConstructors(System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).First();
        var syntaxContext = (GeneratorSyntaxContext)contextCtor.Invoke(new object[] { classDecl, new Lazy<SemanticModel>(() => semanticModel), null! });

        var method = typeof(MessagingIncrementalGenerator).GetMethod("GetHandlerInfo", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!;
        var result = (HandlerDiscoveryInfo?)method.Invoke(null, new object[] { syntaxContext });

        result.Should().BeNull();
    }

    private sealed class NullAttributeData : AttributeData
    {
        protected override INamedTypeSymbol? CommonAttributeClass => null;
        protected override IMethodSymbol? CommonAttributeConstructor => null;
        protected override SyntaxReference? CommonApplicationSyntaxReference => null;
        protected override ImmutableArray<TypedConstant> CommonConstructorArguments => ImmutableArray<TypedConstant>.Empty;
        protected override ImmutableArray<System.Collections.Generic.KeyValuePair<string, TypedConstant>> CommonNamedArguments => ImmutableArray<System.Collections.Generic.KeyValuePair<string, TypedConstant>>.Empty;
    }

    [Fact]
    [System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2075", Justification = "Reflection test")]
    public void ResolveMessageTypeName_WhenAttributeClassIsNull_ReturnsTypeName()
    {
        var attrData = new NullAttributeData();
        var typeSymbol = NSubstitute.Substitute.For<ITypeSymbol>();
        typeSymbol.Name.Returns("FallbackName");
        typeSymbol.GetAttributes().Returns(ImmutableArray.Create<AttributeData>(attrData));

        var method = typeof(MessagingIncrementalGenerator).GetMethod("ResolveMessageTypeName", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!;
        var result = (string)method.Invoke(null, new object[] { typeSymbol })!;

        result.Should().Be("FallbackName");
    }

    [Fact]
    public void HandlerDiscoveryInfo_ConstructorAndProperties_WorkCorrectly()
    {
        // Arrange & Act
        var info = new HandlerDiscoveryInfo(
            handlerFullName: "global::MyNamespace.MyHandler",
            messageFullName: "global::MyNamespace.MyMessage",
            messageTypeName: "custom.message.name",
            handlerName: "MyHandler");

        // Assert
        info.HandlerFullName.Should().Be("global::MyNamespace.MyHandler");
        info.MessageFullName.Should().Be("global::MyNamespace.MyMessage");
        info.MessageTypeName.Should().Be("custom.message.name");
        info.HandlerName.Should().Be("MyHandler");
    }
}



