blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/ericksonlopezf/dotnet-messaging/discussions
    about: Ask questions, discuss architectures, share ideas, and connect with the community.
  - name: 🔒 Security Vulnerability Reporting
    url: https://github.com/ericksonlopezf/dotnet-messaging/security/policy
    about: Privately report a security vulnerability to maintainers.
