<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>AWS SQS message transport for EricksonLopez.Messaging ecosystem.</Description>
    <PackageTags>$(CommonPackageTags);messaging;aws;sqs;aws-sqs;amazon-sqs;queue;broker;message-broker;transport;cloud;native-aot</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EricksonLopez.Messaging\EricksonLopez.Messaging.csproj" />
  </ItemGroup>

</Project>
