// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;

namespace EricksonLopez.Messaging.Generators;

using System.Collections.Immutable;
using System.Linq;
using System.Text;
using EricksonLopez.Messaging.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

/// <summary>
/// Provides an incremental source generator that discovers message handlers at compile time and generates registration code.
/// </summary>
[Generator]
public sealed class MessagingIncrementalGenerator : IIncrementalGenerator
{
    private const string HandlerInterfaceName = "EricksonLopez.Messaging.Contracts.IMessageHandler";
    private const string MessageTypeAttributeName = "EricksonLopez.Messaging.Attributes.MessageTypeAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<HandlerDiscoveryInfo?> handlerDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateClass(s),
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info != null);

        IncrementalValueProvider<ImmutableArray<HandlerDiscoveryInfo?>> collectedHandlers = handlerDeclarations.Collect();

        context.RegisterSourceOutput(collectedHandlers, static (spc, handlers) =>
        {
            var validHandlers = handlers.Where(h => h.HasValue).Select(h => h!.Value).ToList();
            EmitGeneratedRegistrations(spc, validHandlers);
        });
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl &&
               !classDecl.Modifiers.Any(Microsoft.CodeAnalysis.CSharp.SyntaxKind.AbstractKeyword) &&
               classDecl.BaseList != null &&
               classDecl.BaseList.Types.Count > 0;
    }

    private static HandlerDiscoveryInfo? GetHandlerInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (iface.IsGenericType &&
                iface.ConstructedFrom.ToDisplayString().StartsWith(HandlerInterfaceName, StringComparison.Ordinal))
            {
                var messageTypeSymbol = iface.TypeArguments[0];
                var messageTypeName = ResolveMessageTypeName(messageTypeSymbol);

                return new HandlerDiscoveryInfo(
                    handlerFullName: classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    messageFullName: messageTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    messageTypeName: messageTypeName,
                    handlerName: classSymbol.Name);
            }
        }

        return null;
    }

    private static string ResolveMessageTypeName(ITypeSymbol messageTypeSymbol)
    {
        foreach (var attr in messageTypeSymbol.GetAttributes())
        {
            var attrClass = attr.AttributeClass;
            if (attrClass != null &&
                (string.Equals(attrClass.ToDisplayString(), MessageTypeAttributeName, StringComparison.Ordinal) ||
                 string.Equals(attrClass.Name, "MessageTypeAttribute", StringComparison.Ordinal)))
            {
                if (attr.ConstructorArguments.Length > 0 &&
                    attr.ConstructorArguments[0].Value is string customName)
                {
                    return customName;
                }

                if (attr.ApplicationSyntaxReference?.GetSyntax() is AttributeSyntax attrSyntax &&
                    attrSyntax.ArgumentList?.Arguments.Count > 0 &&
                    attrSyntax.ArgumentList.Arguments[0].Expression is LiteralExpressionSyntax lit)
                {
                    return lit.Token.ValueText;
                }
            }
        }

        return messageTypeSymbol.Name;
    }

    private static void EmitGeneratedRegistrations(SourceProductionContext context, List<HandlerDiscoveryInfo> handlers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var messageTypes = handlers
            .Select(h => h.MessageFullName)
            .Distinct(StringComparer.Ordinal)
            .ToList();

        sb.AppendLine("namespace EricksonLopez.Messaging.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Compile-time source-generated JsonSerializerContext for discovered message types.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [JsonSourceGenerationOptions(");
        sb.AppendLine("        WriteIndented = false,");
        sb.AppendLine("        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,");
        sb.AppendLine("        PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,");
        sb.AppendLine("        GenerationMode = JsonSourceGenerationMode.Default)]");

        foreach (var msgType in messageTypes)
        {
            sb.AppendLine($"    [JsonSerializable(typeof({msgType}))]");
        }

        sb.AppendLine("    internal sealed partial class GeneratedMessagingJsonSerializerContext : JsonSerializerContext");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    using System;");
        sb.AppendLine("    using EricksonLopez.Messaging.Contracts;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Compile-time generated extensions for zero-reflection messaging handler registration.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class GeneratedMessagingServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers all compile-time discovered message handlers and JSON serialization context without runtime reflection.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddGeneratedMessagingHandlers(this IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine("            services.AddSingleton<System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver>(");
        sb.AppendLine("                EricksonLopez.Messaging.Generated.GeneratedMessagingJsonSerializerContext.Default);");
        sb.AppendLine();

        foreach (var handler in handlers)
        {
            sb.AppendLine($"            // Handler for message '{handler.MessageTypeName}'");
            sb.AppendLine($"            services.AddMessageHandler<{handler.MessageFullName}, {handler.HandlerFullName}>();");
        }

        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedMessagingExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}


